### PR TITLE
Second draft visualizer 20190323

### PR DESCRIPTION
**Pull request by Mulesoft-Mysti**
@asimons-mule and @taylordolan : If this first draft is close to correct, I'll finish revising the release notes and send that for review under a different PR. 

Ashley, in a few places it seemed easier on the user to just repeat whole procedures. Feel free to tell me if you disagree.  And this is only the changes for 3/23, is that okay? Should I add 3/25 and just note the dates?

### CODE REVIEW

**Review by asimons-mule — COMMENTED** [review]
I think it's **so much clearer**! Thank you for all of the changes. A few thoughts:

1) CloudHub sections says "Verify Supported CloudHub Mule Runtime Engine (Mule)" and Standalone says "Verify Supported Standalone Mule Version." Should we make this consistent? And should it be plural?
2) Let's take advantage of this awesome new layout and clarify things for the user even more:
New title: Verify Which Runtimes Support Metrics
Add to body: The metrics that Visualizer displays come from Anypoint Monitoring. As a result, metrics are only shown in Visualizer for applications running on these Mule versions
3) Under Enable the Monitoring agent section: "If you upgrade to Mule version 4.1.x released after March 23, 2019, you must enable the Monitoring agent in order for your application appear in Visualizer and for metrics to be displayed." 

Otherwise it's great!

**Comment by asimons-mule** [comment]
@taylordolan - please confirm that the changes to these headers will not affect the link in your announcement!
@Mulesoft-Mysti - you should also be aware that we link to docs from the Visualizer UI. Don't want any of these links to break with our section changes.
I checked and the only one that could be affected is:
https://docs.mulesoft.com/visualizer/setup#verify-supported-runtimes

**Comment by Mulesoft-Mysti** [comment]
The general rule is spell it out once in first occurrence, but in this case I agree, will make headings parallel, and the other improvements are great. Will make sure I coordinate with Taylor. I can't get a redirect in place in time, so if need be, will roll back that title. Thank you for checking!

**Comment by Mulesoft-Mysti** [comment]
File names are far more persistent than headings, we might consider a best practice of only linking to the file name from the UI. Or creating an alias system (IDs?) so that changes can be made easily. Studio might do that already.

**Review by asimons-mule — APPROVED** [review]
Think it looks great now! Thank you for your hard work :)

**Pull request merged**
